[package]
name = "file_search"
version = "0.1.0"
authors = ["seino2005 <yagami.zaregoto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"